version: '3.1'
services:
  stars_task:  # 会自动从Docker Hub上自动获取mongo这个镜像
    build: .
    restart: always
    ports:
    - 5000:5000  # 本地端口(可自定义):容器内默认端口(5000)
    links:
    - mongo
    depends_on:
    - mongo
    environment:
      SECRET_KEY: hard to guess
      MAIL_PASSWORD: your email password
      FLASK_ENV: production


  mongo:  # 会自动从Docker Hub上自动获取mongo这个镜像
    image: suanmilk/mongo
    restart: always
    ports:
    - 27017:27017  # 本地端口(可自定义):容器内默认端口(mongo设定为27017)
    environment:  # admin账号和密码
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 2010415108

  # 如果不需要MongoDB的网页端，以下内容可以不加
  mongo-express:  # 会自动从Docker Hub上自动获取mongo-express这个镜像
    image: mongo-express
    restart: always
    ports:
    - 8080:8081  # 本地端口(可自定义):容器内默认端口(mongo-express设定为8080)
    environment:  # 这里只能使用与上方MONGO_INITDB_ROOT_USERNAME相同的root账号
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2010415108
